### ISSUE TITLE
For typing character that's not in Latin, URL Bar is bugging out

### ISSUE THREAD

**Issue by ecruosnepo** [Shina-SG/Shina-Fox#22]
https://github.com/Shina-SG/Shina-Fox/assets/67457511/7f81c8e1-3a65-4465-a4d1-02bb7629c38d

Hello.
I'm using the file you shared well.
But I have a small problem, so I'm asking you a question.
It's okay when I type in English in url bar,
When I type in Korean, the same symptoms as the video appear.
Is there a solution?
If there's no way, can't you just fix it on top?

**Comment by Shina-SG** [comment]
seems like a firefox bug right here https://bugzilla.mozilla.org/show_bug.cgi?id=1751639 and the fix is go to `about:config` and change `keepPanelOpenDuringImeComposition` to `true`

**Comment by ecruosnepo** [comment]
I apologize for writing the title strangely due to my poor English skills.
Nevertheless, you are truly an angel for kindly correcting the title.
I changed the settings as you suggested and it returned to normal.
Thank you so much.
I hope the new year is filled with only good things for you.
