### ISSUE TITLE
Right sidebar

### ISSUE THREAD

**Issue by zaeboba** [Shina-SG/Shina-Fox#26]
Not quite figured out how to make a right sidebar, as you have in the pictures, and also did not understand how to divide the window into two parts
![изображение](https://github.com/Shina-SG/Shina-Fox/assets/57330346/ae46c3a3-ff1c-4471-9789-6e3648fd98f4)
Can you give me a tutorial on how to do that? Or hotkeys.

By the way, I never understood what is meant by "Custom Icon" and how to customize it, I have SingleFileZ on the right button.

**Comment by Rigerhit047** [comment]
The right side bar is a Floorp (Firefox fork) thing, although I don't know what you meant with the rest

**Comment by zaeboba** [comment]
> Правая боковая панель — это Floorp (вилка Firefox), хотя я не знаю, что вы имели в виду под остальными.

two pages in one window

**Comment by alybye** [comment]
> > Правая боковая панель — это Floorp (вилка Firefox), хотя я не знаю, что вы имели в виду под остальными.
> 
> two pages in one window

That's also a floorp feature. Firefox cannot split tabs.

**Comment by zaeboba** [comment]
thx


> > two pages in one window
> 
> That's also a floorp feature. Firefox cannot split tabs.

**Comment by rajb16** [comment]
https://pastebin.com/1wT1BYWV

I was able to do this.

![image](https://github.com/user-attachments/assets/a578b5c8-f977-4b84-afb9-41813673452c)
